# .graphclientrc.yml
sources:
  - name: honey-dashboard-polygon
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/tomjpandolfi/honey-dashboard-polygon

documents:
  - ./graphql/**/*.graphql
